[package]
name = "cp39_conways_game_of_life"
version = "0.1.0"
authors = ["Jonathan <jonathanwoollettlight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
